server:
    port: 8080

zuul:
  routes:
    campanha:
      path: /campanha/**
      serviceId: CAMPANHA-SERVICE
      stripPrefix: false
    associacao:
      path: /associacao/**
      serviceId: CAMPANHA-SERVICE
      stripPrefix: false
    socioTorcedor:
      path: /sociotorcedor/**
      serviceId: SOCIO-TORCEDOR-SERVICE
      stripPrefix: false

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/